<?php
$cmd=$_POST['cmd'];
$mc_gross=$_POST['mc_gross'];
$protection_eligibility=$_POST['protection_eligibility'];
$address_status=$_POST['address_status'];
$payer_id=$_POST['payer_id'];
$tax=$_POST['tax'];
$address_street=$_POST['address_street'];
$payment_date=$_POST['payment_date'];
$payment_status=$_POST['payment_status'];
$charset=$_POST['charset'];
$address_zip=$_POST['address_zip'];
$first_name=$_POST['first_name'];
$option_selection1=$_POST['option_selection1'];
$option_selection2=$_POST['option_selection2'];
$address_country_code=$_POST['address_country_code'];
$address_name=$_POST['address_name'];
$notify_version=$_POST['notify_version'];
$custom=$_POST['custom'];
$payer_status=$_POST['payer_status'];
$business=$_POST['business'];
$address_country=$_POST['address_country'];
$address_city=$_POST['address_city'];
$quantity=$_POST['quantity'];
$verify_sign=$_POST['verify_sign'];
$payer_email=$_POST['payer_email'];
$option_name1=$_POST['option_name1'];
$option_name2=$_POST['option_name2'];
$txn_id=$_POST['txn_id'];
$payment_type=$_POST['payment_type'];
$btn_id=$_POST['btn_id'];
$last_name=$_POST['last_name'];
$address_state=$_POST['address_state'];
$receiver_email=$_POST['receiver_email'];
$shipping_discount=$_POST['shipping_discount'];
$insurance_amount=$_POST['insurance_amount'];
$receiver_id=$_POST['receiver_id'];
$pending_reason=$_POST['pending_reason'];
$txn_type=$_POST['txn_type'];
$item_name=$_POST['item_name'];
$discount=$_POST['discount'];
$mc_currency=$_POST['mc_currency'];
$item_number=$_POST['item_number'];
$residence_country=$_POST['residence_country'];
$test_ipn=$_POST['test_ipn'];
$receipt_id=$_POST['receipt_id'];
$shipping_method=$_POST['shipping_method'];
$handling_amount=$_POST['handling_amount'];
$transaction_subject=$_POST['transaction_subject'];
$payment_gross=$_POST['payment_gross'];
$shipping=$_POST['shipping'];
$ipn_track_id=$_POST['ipn_track_id'];

$string=$option_selection1;
$s = explode("&",$string);
foreach( $s as $k=>$v){
  $v=explode("=",$v);
  $a[$v[0]]=$v[1];
}
extract($a);

?>